bookmarkproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('bookmarks/', include('bookmarksapp.urls')),
    path('', RedirectView.as_view(url='bookmarks/')),
    path('admin/', admin.site.urls),
]

bookmarksapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/delete/', views.Deletebookmarks, name='delete-bookmarks'),
    path('<int:pk>/bookmarkdetail/', views.Detailbookmarks, name='detail-bookmarks'),
    path('<int:pk>/bookmarkupdate/', views.Updatebookmarks, name='update-bookmarks'),
    path('<int:pk>/folder/', views.FolderList, name='list-folder'),
    path('folderunknown/', views.FolderListUnknown, name='list-folder-unknown'),
    path('<int:pk>/delete/folder', views.Deletefolder, name='delete-folder'),
    path('<int:pk>/update/folder', views.Updatefolder, name='update-folder'),
]

bookmarksapp/models.py
from django.db import models
from taggit.managers import TaggableManager


class Bookmarks(models.Model):
    """Model representing a Bookmarks."""
    name = models.CharField(max_length=200, help_text='Enter a webpage name')
    url = models.CharField(max_length=200, help_text='Enter a webpage url')
    description = models.CharField(max_length=200, help_text='Enter a webpage description')
    tags = TaggableManager(help_text='Enter webpage tags')
    folder = models.ForeignKey('Folder', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Folder(models.Model):
    """Model representing a Folder"""
    name = models.CharField(max_length=200, help_text='Enter the folder name')

    def __str__(self):
        """String for representing the Model object."""
        return self.name

bookmarksapp/forms.py
from django import forms
from .models import Bookmarks, Folder


class BookmarkForms(forms.ModelForm):

    class Meta:
        model = Bookmarks
        fields = ['name','url','description','tags','folder']

class FolderForm(forms.ModelForm):

    class Meta:
        model = Folder
        fields = ['name']

bookmarksapp/views.py
from django.shortcuts import render
from .models import Bookmarks, Folder
from .filters import BookmarksFilter
from .forms import BookmarkForms, FolderForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404


def index(request):
    """View function for home page of site."""

    bookmarks = Bookmarks.objects.all()
    namefilter = BookmarksFilter(request.GET, queryset=bookmarks)
    folder_list = Folder.objects.all()
    if(request.POST):
        bookmarkform = BookmarkForms(request.POST)
        folderform = FolderForm(request.POST)
    else:
        bookmarkform = BookmarkForms(initial={'url':'https://www.'})
        folderform = FolderForm()
    if (bookmarkform.is_valid()):
        bookmarkform.save()
        return HttpResponseRedirect(reverse('index'))
    if (folderform.is_valid()):
        folderform.save()
        return HttpResponseRedirect(reverse('index'))
    context = {
        'filter': namefilter,
        'folder_list': folder_list,
        'bookmarkform': bookmarkform,
        'folderform': folderform,
    }
    return render(request, 'bookmarksapp/index.html', context=context)


def Deletebookmarks(request,pk):
    Bookmarks.objects.get(pk=pk).delete()
    return HttpResponseRedirect(reverse('index'))


def Detailbookmarks(request,pk):
    """View function for Detail bookmark"""
    folder_list = Folder.objects.all()
    bookmark = get_object_or_404(Bookmarks,pk=pk)
    context = {
        'folder_list': folder_list,
        'bookmark': bookmark,
    }
    return render(request, 'bookmarksapp/detail_bookmark.html', context=context)

def Updatebookmarks(request,pk):
    """View function for Detail bookmark"""
    folder_list = Folder.objects.all()
    bookmark = get_object_or_404(Bookmarks,pk=pk)
    if (request.POST):
        bookmarkform = BookmarkForms(request.POST,instance=bookmark)
    else:
        bookmarkform = BookmarkForms(initial={'name':bookmark.name,'url':bookmark.url,'description':bookmark.description,'folder':bookmark.folder,'tags':bookmark.tags.all})
    if(bookmarkform.is_valid()):
        bookmarkform.save()
        return HttpResponseRedirect(reverse('index'))
    context = {
        'folder_list': folder_list,
        'form': bookmarkform,
        'bookmark': bookmark,
    }
    return render(request, 'bookmarksapp/update_bookmark.html', context=context)


def FolderList(request,pk):
    """View function for list Folder bookmark"""
    folder = get_object_or_404(Folder, pk=pk)
    bookmarks = folder.bookmarks_set.all()
    namefilter = BookmarksFilter(request.GET, queryset=bookmarks)
    folder_list = Folder.objects.all()
    if (request.POST):
        bookmarkform = BookmarkForms(request.POST)
        folderform = FolderForm(request.POST)
    else:
        bookmarkform = BookmarkForms(initial={'url': 'https://www.'})
        folderform = FolderForm()
    if (bookmarkform.is_valid()):
        bookmarkform.save()
        return HttpResponseRedirect(reverse('index'))
    if (folderform.is_valid()):
        folderform.save()
        return HttpResponseRedirect(reverse('index'))
    context = {
        'filter': namefilter,
        'folder_list': folder_list,
        'folder': folder,
        'bookmarkform': bookmarkform,
        'folderform': folderform,
    }
    return render(request, 'bookmarksapp/list_folder.html', context=context)

def FolderListUnknown(request):
    """View function for list Folder bookmark"""
    folder_list = Folder.objects.all()
    bookmarks = Bookmarks.objects.filter(folder=None)
    namefilter = BookmarksFilter(request.GET, queryset=bookmarks)
    if (request.POST):
        bookmarkform = BookmarkForms(request.POST)
        folderform = FolderForm(request.POST)
    else:
        bookmarkform = BookmarkForms(initial={'url': 'https://www.'})
        folderform = FolderForm()
    if (bookmarkform.is_valid()):
        bookmarkform.save()
        return HttpResponseRedirect(reverse('index'))
    if (folderform.is_valid()):
        folderform.save()
        return HttpResponseRedirect(reverse('index'))
    context = {
        'filter': namefilter,
        'folder_list': folder_list,
        'bookmarkform': bookmarkform,
        'folderform': folderform,
    }
    return render(request, 'bookmarksapp/list_folder_unknown.html', context=context)

def Deletefolder(request,pk):
    Folder.objects.get(pk=pk).delete()
    return HttpResponseRedirect(reverse('index'))


def Updatefolder(request,pk):
    """View function for Detail bookmark"""
    folder_list = Folder.objects.all()
    folder = get_object_or_404(Folder,pk=pk)
    if (request.POST):
        folderform = FolderForm(request.POST, instance=folder)
    else:
        folderform = FolderForm(initial={'name':folder.name})
    if(folderform.is_valid()):
        folderform.save()
        return HttpResponseRedirect(reverse('list-folder',args=[pk]))
    context = {
        'folder_list': folder_list,
        'form': folderform,
        'folder': folder,
    }
    return render(request, 'bookmarksapp/update_folder.html', context=context)

bookmarksapp/templates/bookmarks.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Bookmarks</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
 <nav class="navbar navbar-expand-lg" style="background-color: blue">
  <div class="container-fluid" >
    <h2 class="navbar-brand" style="color: white;">Bookmarks</h2>
    <div class="input-group container-fluid" style="width: 50%;">
      <form method="get" style="display:flex; width: 100%;">
      <div class="input-group-append">
        <button class="btn" type="submit" style="background-color: darkblue;">
          <i class="fa fa-search" style="color: white;"></i>
        </button>
      </div>
      <input style="background-color:darkblue ; border: darkblue; color: white;" type="text" class="form-control" name="name" id="id_name" placeholder="Bookmarks">
      </form>
    </div>
  <div class="dropdown show">
    <a class="btn" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-ellipsis-v" style="color: white;"></i>
    </a>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
      <a class="btn btn-default btn-rounded" style="display:block" data-toggle="modal" data-target="#modalBookmarkForm" href="" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Add Bookmark</a>
      <a class="btn btn-default btn-rounded" style="display:block" data-toggle="modal" data-target="#modalFolderForm" href="#" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Add Folder</a>
    </div>
  </div>
  </div>
</nav>
<div class="container-fluid">
    <div class="row">
      <div class="mysidebar col-sm-2 pt-2">
        <ul class="sidebar-nav" style="list-style-type: none;">
          <li>Bookmarks Bar
            <ul>
              {% for folder in folder_list %}
              <li><a href="">{{ folder.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          <li>Other Bookmarks
          </li>
        </ul>
      </div>

  <div class="col-sm-10 pt-3">
    {% if filter.qs %}
    <ul class="list-group">
    {% for bookmark in filter.qs %}
        <li class=" list-group-item flex-column align-items-start"><a style="text-decoration: none; color:black;" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'"  href="{{ bookmark.url }}" target="_blank">{{ bookmark.name }}--{{ bookmark.url }}
        <div class="dropdown show" style="display: inline-block; float: right;">
          <a class="btn" href="#" role="button" id="dropdownItemLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-ellipsis-v" style="color: grey;"></i>
          </a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            <a class="btn btn-default btn-rounded" style="display: block;" data-toggle="modal" data-target="#modalLoginForm" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'" href="">Update</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="{% url 'delete-bookmarks' bookmark.id %}" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Delete</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="#" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Detail</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="{{ bookmark.url }}" target="_blank" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Open</a>
          </div>
        </div>
      </a>
        </li>
    {% endfor %}
    </ul>
  {% else %}
    <p>There are no bookmarks.</p>
  {% endif %}
    </div>
  </div>
</div>
<div class="modal fade" id="modalBookmarkForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title">Create Bookmarks</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <form action="" method="post">
          {% csrf_token %}
          <table>
            {{ bookmarkform.as_table }}
          </table>
          <div class="modal-footer d-flex justify-content-center">
          <input type="submit" value="Submit">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modalFolderForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title">Create Folder</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <form action="" method="post">
          {% csrf_token %}
          <table>
            {{ folderform.as_table }}
          </table>
          <div class="modal-footer d-flex justify-content-center">
          <input type="submit" value="Submit">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</body>
</html>

bookmarksapp/templates/bookmarksapp/detail_bookmark.html
{% extends "base_generic.html" %}

{% block content %}
  <button style="border-radius: 50%;border-color: black;" disabled>
    <a href="{% url 'index' %}">
    <i class="fa fa-arrow-left" onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" ></i>
    </a>
  </button>
  <button style="border-color: black;" disabled>
    <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{% url 'delete-bookmarks' bookmark.id %}" style="text-decoration: none;">Delete
    </a>
  </button>
  <button style="border-color: black;" disabled>
    <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{{ bookmark.url }}" target="_blank" style="text-decoration: none;">Open Page
    </a>
  </button>
  <button style="border-color: black;" disabled>
    <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{% url 'update-bookmarks' bookmark.id %}" style="text-decoration: none;">Update
    </a>
  </button>
  <br><br>
  <h3>Bookmark Detail</h3>
  <p><strong>Name: </strong>{{ bookmark.name }}</p>
  <p><strong>URL: </strong><a href="{{ bookmark.url }}" target="_blank">{{ bookmark.url }}</a></p>
  <p><strong>Folder: </strong>{{ bookmark.folder }}</p>
  <p><strong>Description: </strong>{{ bookmark.description }}</p>
  <p><strong>Tags: </strong>
    <ul>
    {% for bookmarks in bookmark.tags.all %}
    <li>{{ bookmarks.name }}</li>
    {% endfor %}
    </ul>
  </p>
{% endblock %}

bookmarksapp/templates/bookmarksapp/index.html
{% extends "base_generic.html" %}

{% block search %}

<div class="input-group container-fluid" style="width: 50%;">
      <form method="get" style="display:flex; width: 100%;">
      <div class="input-group-append">
        <button class="btn" type="submit" style="background-color: darkblue;">
          <i class="fa fa-search" style="color: white;"></i>
        </button>
      </div>
      <input style="background-color:darkblue ; border: darkblue; color: white;" type="text" class="form-control" name="name" id="id_name" placeholder="Bookmarks">
      </form>
    </div>

{% endblock %}

{% block create %}
<div class="dropdown show">
    <a class="btn" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-ellipsis-v" style="color: white;"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
      <a class="btn btn-default btn-rounded" style="display:block" data-toggle="modal" data-target="#modalBookmarkForm" href="" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Add Bookmark</a>
      <a class="btn btn-default btn-rounded" style="display:block" data-toggle="modal" data-target="#modalFolderForm" href="#" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Add Folder</a>
    </div>
</div>
{% endblock %}

{% block content %}
    {% if filter.qs %}
    <ul class="list-group">
    {% for bookmark in filter.qs %}
        <li class=" list-group-item flex-column align-items-start"><a style="text-decoration: none; color:black;" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'"  href="{{ bookmark.url }}" target="_blank"><strong>{{ bookmark.name }}</strong><span> | {{ bookmark.url }}</span>
        <div class="dropdown show" style="display: inline-block; float: right;">
          <a class="btn" href="#" role="button" id="dropdownItemLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-ellipsis-v" style="color: grey;"></i>
          </a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            <a class="btn btn-default btn-rounded" style="display: block;" href="{% url 'update-bookmarks' bookmark.id %}" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Update</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="{% url 'delete-bookmarks' bookmark.id %}" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Delete</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="{% url 'detail-bookmarks' bookmark.id %}" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Detail</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="{{ bookmark.url }}" target="_blank" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Open</a>
          </div>
        </div>
      </a>
        </li>
    {% endfor %}
    </ul>
  {% else %}
    <p>There are no bookmarks.</p>
  {% endif %}
{% endblock %}

bookmarksapp/templates/bookmarksapp/list_folder.html
{% extends "base_generic.html" %}

{% block search %}

<div class="input-group container-fluid" style="width: 50%;">
      <form method="get" style="display:flex; width: 100%;">
      <div class="input-group-append">
        <button class="btn" type="submit" style="background-color: darkblue;">
          <i class="fa fa-search" style="color: white;"></i>
        </button>
      </div>
      <input style="background-color:darkblue ; border: darkblue; color: white;" type="text" class="form-control" name="name" id="id_name" placeholder="Bookmarks">
      </form>
    </div>

{% endblock %}

{% block create %}
<div class="dropdown show">
    <a class="btn" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-ellipsis-v" style="color: white;"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
      <a class="btn btn-default btn-rounded" style="display:block" data-toggle="modal" data-target="#modalBookmarkForm" href="" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Add Bookmark</a>
      <a class="btn btn-default btn-rounded" style="display:block" data-toggle="modal" data-target="#modalFolderForm" href="#" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Add Folder</a>
    </div>
</div>
{% endblock %}

{% block content %}
    <button style="border-color: black;" disabled>
        <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{% url 'delete-folder' folder.id %}" style="text-decoration: none;">Delete Folder
        </a>
    </button>
    <button style="border-color: black;" disabled>
        <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{% url 'update-folder' folder.id %}" style="text-decoration: none;">Update Folder
        </a>
    </button>
    <br><br>
    {% if filter.qs %}
    <ul class="list-group">
    {% for bookmark in filter.qs %}
        <li class=" list-group-item flex-column align-items-start"><a style="text-decoration: none; color:black;" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'"  href="{{ bookmark.url }}" target="_blank"><strong>{{ bookmark.name }}</strong><span> | {{ bookmark.url }}</span>
        <div class="dropdown show" style="display: inline-block; float: right;">
          <a class="btn" href="#" role="button" id="dropdownItemLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-ellipsis-v" style="color: grey;"></i>
          </a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            <a class="btn btn-default btn-rounded" style="display: block;" href="{% url 'update-bookmarks' bookmark.id %}" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Update</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="{% url 'delete-bookmarks' bookmark.id %}" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Delete</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="{% url 'detail-bookmarks' bookmark.id %}" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Detail</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="{{ bookmark.url }}" target="_blank" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Open</a>
          </div>
        </div>
      </a>
        </li>
    {% endfor %}
    </ul>
  {% else %}
    <p>There are no bookmarks.</p>
  {% endif %}
{% endblock %}

bookmarksapp/templates/bookmarksapp/list_folder_unknown.html
{% extends "base_generic.html" %}

{% block search %}

<div class="input-group container-fluid" style="width: 50%;">
      <form method="get" style="display:flex; width: 100%;">
      <div class="input-group-append">
        <button class="btn" type="submit" style="background-color: darkblue;">
          <i class="fa fa-search" style="color: white;"></i>
        </button>
      </div>
      <input style="background-color:darkblue ; border: darkblue; color: white;" type="text" class="form-control" name="name" id="id_name" placeholder="Bookmarks">
      </form>
    </div>

{% endblock %}

{% block create %}
<div class="dropdown show">
    <a class="btn" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-ellipsis-v" style="color: white;"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
      <a class="btn btn-default btn-rounded" style="display:block" data-toggle="modal" data-target="#modalBookmarkForm" href="" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Add Bookmark</a>
      <a class="btn btn-default btn-rounded" style="display:block" data-toggle="modal" data-target="#modalFolderForm" href="#" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Add Folder</a>
    </div>
</div>
{% endblock %}

{% block content %}
    {% if filter.qs %}
    <ul class="list-group">
    {% for bookmark in filter.qs %}
        <li class=" list-group-item flex-column align-items-start"><a style="text-decoration: none; color:black;" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'"  href="{{ bookmark.url }}" target="_blank"><strong>{{ bookmark.name }}</strong><span> | {{ bookmark.url }}</span>
        <div class="dropdown show" style="display: inline-block; float: right;">
          <a class="btn" href="#" role="button" id="dropdownItemLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-ellipsis-v" style="color: grey;"></i>
          </a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            <a class="btn btn-default btn-rounded" style="display: block;" href="{% url 'update-bookmarks' bookmark.id %}" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Update</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="{% url 'delete-bookmarks' bookmark.id %}" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Delete</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="{% url 'detail-bookmarks' bookmark.id %}" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Detail</a>
            <a class="btn btn-default btn-rounded" style="display: block;" href="{{ bookmark.url }}" target="_blank" onmouseover = "this.style.color = 'blue'" onmouseout = "this.style.color = 'black'">Open</a>
          </div>
        </div>
      </a>
        </li>
    {% endfor %}
    </ul>
  {% else %}
    <p>There are no bookmarks.</p>
  {% endif %}
{% endblock %}

bookmarksapp/templates/bookmarksapp/update_bookmark.html
{% extends "base_generic.html" %}

{% block content %}
  <button style="border-radius: 50%;border-color: black;" disabled>
    <a href="{% url 'index' %}">
    <i class="fa fa-arrow-left" onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" ></i>
    </a>
  </button>
  <button style="border-color: black;" disabled>
    <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{% url 'delete-bookmarks' bookmark.id %}" style="text-decoration: none;">Delete
    </a>
  </button>
  <br><br>
  <h3>Update Bookmark</h3>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}